/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AiPicksRouteImport } from './routes/ai-picks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticleArticleIdRouteImport } from './routes/article/$articleId'

const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPicksRoute = AiPicksRouteImport.update({
  id: '/ai-picks',
  path: '/ai-picks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleArticleIdRoute = ArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-picks': typeof AiPicksRoute
  '/ask': typeof AskRoute
  '/browse': typeof BrowseRoute
  '/roles': typeof RolesRoute
  '/article/$articleId': typeof ArticleArticleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-picks': typeof AiPicksRoute
  '/ask': typeof AskRoute
  '/browse': typeof BrowseRoute
  '/roles': typeof RolesRoute
  '/article/$articleId': typeof ArticleArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-picks': typeof AiPicksRoute
  '/ask': typeof AskRoute
  '/browse': typeof BrowseRoute
  '/roles': typeof RolesRoute
  '/article/$articleId': typeof ArticleArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-picks'
    | '/ask'
    | '/browse'
    | '/roles'
    | '/article/$articleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-picks' | '/ask' | '/browse' | '/roles' | '/article/$articleId'
  id:
    | '__root__'
    | '/'
    | '/ai-picks'
    | '/ask'
    | '/browse'
    | '/roles'
    | '/article/$articleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiPicksRoute: typeof AiPicksRoute
  AskRoute: typeof AskRoute
  BrowseRoute: typeof BrowseRoute
  RolesRoute: typeof RolesRoute
  ArticleArticleIdRoute: typeof ArticleArticleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-picks': {
      id: '/ai-picks'
      path: '/ai-picks'
      fullPath: '/ai-picks'
      preLoaderRoute: typeof AiPicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$articleId': {
      id: '/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/article/$articleId'
      preLoaderRoute: typeof ArticleArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiPicksRoute: AiPicksRoute,
  AskRoute: AskRoute,
  BrowseRoute: BrowseRoute,
  RolesRoute: RolesRoute,
  ArticleArticleIdRoute: ArticleArticleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
